#!/bin/sh
. "$(dirname "$0")/_/husky.sh" # husky stuff

# Load conda.sh to use conda commands in this script
. C:/tools/miniconda3/etc/profile.d/conda.sh

# Variables
OVERWRITE='\e[1A\e[K'
CHECK_MARK='\033[0;32m✓\033[0m'
CROSS_MARK='\033[0;31m✘\033[0m'
WARNING='\033[1;33m!\033[0m'
ADD_MARK='\033[0;34m+\033[0m'
COMMIT_MARK='\033[1;35m→\033[0m'

# Check activation of the environment
check_environment() {
  if ! [ $CONDA_SHLVL = 1 ]; then
    # Activate the environment since it is deactivated, print status
    printf "Activating ${ENVIRONMENT}...\n" &&
      conda activate ./noodles &&
      printf "${OVERWRITE}${CHECK_MARK} Activated\n"
  else
    # Pass, print status
    printf "${CHECK_MARK} ${ENVIRONMENT} Already active\n"
  fi

  return
}

# Invoke conda to export environment to environment.yaml
call_conda() {
  # take environment name as arguments
  ENVIRONMENT="$1"

  check_environment

  # Export environment to .yaml
  printf "Exporting to ${ENVIRONMENT}_temp.yaml...\n" &&
    conda env export >noodles_temp.yaml &&
    printf "${OVERWRITE}${CHECK_MARK} Exported ${ENVIRONMENT}_temp.yaml\n"

  # Deactivate environment
  printf "Deactivating ${ENVIRONMENT}...\n" &&
    conda deactivate &&
    printf "${OVERWRITE}${CHECK_MARK} Deactivated\n"

  return
}

# Exporting environment to same file will always results in a true if(changed)
# Workaround: export to temp file, compare files then act accordingly
check_diff() {
  # Add empty line, acts as a separator
  printf "\n"

  if cmp -s "./${ENVIRONMENT}.yaml" "./${ENVIRONMENT}_temp.yaml"; then
    # File unchanged, allow push
    printf "${CHECK_MARK} Environment unchanged\n"

    printf "${CHECK_MARK} Allowing push\n" &&
      rm ./${ENVIRONMENT}_temp.yaml # Remove temp file
  else
    # File changed, replace and deny push
    printf "${WARNING} Environment changed\n"

    # Rename temp to noodles.yaml
    mv ./${ENVIRONMENT}_temp.yaml ./${ENVIRONMENT}.yaml

    # Track changes
    printf "${ADD_MARK} Tracking changes\n" &&
      git add ./${ENVIRONMENT}.yaml

    # Commit changes, can edit with `git commit --amend`
    printf "${COMMIT_MARK} Committing changes (edit: git commit --amend)\n" &&
      git commit -m "feat(env): auto-updated \`${ENVIRONMENT}.yaml\`"

    # Add empty line, acts as a separator
    printf "\n"
    # Deny push, make user push again

    # TODO: Add the possibility to push even if files differ
    printf "${CROSS_MARK} Denying push\n"

    # Push denied => 126: "command not executable"
    exit 126
  fi

  return
}

main() {
  call_conda noodles
  check_diff

  return
}

main
